### PR TITLE
Create README.fr.md

### PR DESCRIPTION
**Pull request by kushal34712**
added french translation for readme.md file

### CODE REVIEW

**Comment by zhoushaw** [comment]
@kushal34712 Thank you for your contribution. However, if the future maintenance of our readme in many languages will cause problems for our maintenance, we suggest that you can read it in English through direct translation

**Comment by zhoushaw** [comment]
It can be read by translating English into the target language

**Comment by kushal34712** [comment]
sir can u tell me what i have to do

**Comment by zhoushaw** [comment]
@kushal34712 If you are interested in contributing to midscene, please help us read more English documents, and improve the English documents, I believe it will help

**Pull request closed without merging**
